openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:18087
    description: Generated server url
paths:
  /version/:
    get:
      tags:
        - version-rest-controller
      operationId: versionInformation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
components: { }
