version: "3"
services:
  db_schedule_db:
    image: postgres:latest
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: is
